Update Docker instructions
friendsofgo/killgrave pull request #84
Opened 2021-02-23 02:57 UTC by bunsenmcdubbs

Two changes:
1. Add `-h 0.0.0.0` to the Docker command in order for the instructions to actually work and respond to `curl`'s from the host machine. This is a project-specific sharp edge since Killgrave defaults to `localhost` and therefore will not work out of the box using the original command.
2. (I'm ok with reverting this) Remove vague warning about Docker networking and note about `-p` flag. IMO this is table-stakes Docker knowledge not well suited for a project-specific documentation (possibly belongs in a more fleshed out example). Put another way, why not also document the `-v` volume mount and the `-w` working directory change? Seems like none of it should be included here.

2021-02-25 18:50 UTC, joanlopez requested changes
Hey @bunsenmcdubbs, thanks for contributing!

I agree the `-h 0.0.0.0` clarification is helpful.
However, I cannot see a reason for removing the `-p` comment, instead I'd try to write it in a more clear way.

As you mentioned, it does not make sense to document here all the available Docker flags. However, someone could get stuck on trying to use the Killgrave flag to specify another port but without forwarding it at Docker level, in a similar way as it happens with the `localhost` So, that's the reason I think it really worth to keep it.

Thanks!!

2021-03-06 06:30 UTC, bunsenmcdubbs commented
Thanks for the feedback @joanlopez! I've re-added a revised version of the `-p` documentation (and also threw in some small reformatting/edits for nearby documentation)

2021-03-08 17:11 UTC, joanlopez approved these changes
Now I think it looks much better! 🚀  Again, thanks for engaging!! 🙏🏻 
Feel free to have a look and contribute to the codebase! 👌🏻 
We're currently focused on the `v0.4.1` and `v0.5.0` releases 🔥

2021-03-08 17:12 UTC, merged

2021-05-26 15:52 UTC, hitokiri commented
I have the next problem; you say to use this line to can run the Docker image
docker run -it --rm -p 3000:3000 -v $PWD/:/home -w /home friendsofgo/killgrave -h 0.0.0.0

but when y run this with this tree configuration
mymock/
    imposters/
        config.yml
        swapi_people.imp.json
        swapi_planets.imp.json

the image logs return the next message
![image](https://user-images.githubusercontent.com/247528/119691374-c0957180-be07-11eb-98a9-e912b6479b27.png)

2021-05-27 11:49 UTC, joanlopez commented
> I have the next problem; you say to use this line to can run the Docker image
> docker run -it --rm -p 3000:3000 -v $PWD/:/home -w /home friendsofgo/killgrave -h 0.0.0.0
> 
> but when y run this with this tree configuration
> mymock/
> imposters/
> config.yml
> swapi_people.imp.json
> swapi_planets.imp.json
> 
> the image logs return the next message
> ![image](https://user-images.githubusercontent.com/247528/119691374-c0957180-be07-11eb-98a9-e912b6479b27.png)

Hey @hitokiri,
Thanks for reaching. Could you create an issue to keep track of it? Thanks!! 🙏🏻